server:
  port: 6019
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: alex-ai
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: deepseek-r1:32b
          temperature: 0.7
    vectorstore:
      milvus:
        initialize-schema: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/alex_rag?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
milvus:
  baseUrl: http://127.0.0.1:19530
deepseek:
  model: deepseek-r1:32b
  temperature: 0.7
qwen:
  model: qwen:2.5b
  temperature: 0.7