server:
  port: 6019
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: alex-ai
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: deepseek-r1:32b
          temperature: 0.7
          #model: qwen:0.5b
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
milvus:
  baseUrl: http://127.0.0.1:19530