server:
  port: 6019
  tomcat:
    max-swallow-size: 100MB
spring:
  application:
    name: alex-ai
  ai:
    ollama:
      base-url: http://192.168.100.179:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.7
          #model: qwen:0.5b
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
ai:
  api_key: sk-2e0fd07d52504d1d8cf5d29d125e2e0f
  # api_key: sk-6c075959f19a467388c8741e0955785c
# rocketmq:
#   name-server: 127.0.0.1:9876
#   producer:
#     group: alexAiProducer
#   consumer:
#     group: alexAiConsumer
